renegade_car_impact_homepage:
    pattern:  /
    defaults: { _controller: RenegadeCarImpactBundle:Default:index }


renegade_car_impact_api_v1:
    resource: "@RenegadeCarImpactBundle/Resources/config/routing/api_v1.yml"
    prefix:   /api/v1/

